//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.1
//     from Assets/Settings/BraidInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @BraidInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BraidInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BraidInputActions"",
    ""maps"": [
        {
            ""name"": ""SideScrollMap"",
            ""id"": ""6788ca14-c235-466b-b785-5f781262bc37"",
            ""actions"": [
                {
                    ""name"": ""HorizontalMovement"",
                    ""type"": ""Value"",
                    ""id"": ""e871dc87-227a-4ff9-b879-bc98431e2d65"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""0c8f8d8e-f589-494a-b05d-45672446bb7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rewind"",
                    ""type"": ""Button"",
                    ""id"": ""f0e6ddba-fb7e-4504-9fac-10a7215cba56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""871c3c18-9475-45e7-9af5-e44ca7f29db5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUpDrop"",
                    ""type"": ""Button"",
                    ""id"": ""ecb5c149-83bd-4f01-bd86-bd43bbbaed6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseRewindSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""7a9c950a-1c0b-427b-8825-6a362f770ebe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreaseRewindSpeed1"",
                    ""type"": ""Button"",
                    ""id"": ""db6b16b1-6eca-43cf-bd5a-1f7c6bdeaf01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""LeftRightArrow"",
                    ""id"": ""581be5ec-121b-4879-ac04-c7cc77ded203"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1700dd18-78bc-4d3c-b7b1-f11afe98fcf6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f66e391e-bdb2-4a93-acbb-088a136c18ce"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ADButtons"",
                    ""id"": ""2c238913-5bde-4fff-afae-eb7d3a8031db"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fa818bcb-cf7b-4854-bdff-416e4401527f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""831af261-22d0-4b76-8e60-3f5d9c88a58c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4bcc4301-4383-400b-9fec-36067f704559"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""302510a6-702c-4291-9217-7abb651d92f6"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe4ac294-88ca-4fd2-98c1-efc6f2c62534"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rewind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3ff646c-845c-485f-9a9a-385ea38f8692"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20284b1f-d6d0-4d13-a89c-c1f738d064d7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickUpDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""7964aaac-fb2b-498b-976a-e269a19e21c0"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseRewindSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""16bbb568-80d1-4f4b-8003-7d71d8882d37"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseRewindSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b013ec07-7bed-4ac4-ad9d-ef9eaeb2e95b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseRewindSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""4db0a8aa-7e7b-47cc-a60c-2c194d272911"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseRewindSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""772f9370-f8d8-41bc-8f6c-8176b8b254b4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseRewindSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0924c299-108f-410c-9373-4b5dc045d49d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseRewindSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""942144ce-a882-45f6-90bd-a3c873af9d5a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseRewindSpeed1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0f0a02e1-144b-4188-8255-f65c2c1cf532"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseRewindSpeed1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""88dec8b0-8e19-4cf2-8752-cae0adef6b6f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseRewindSpeed1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a879b5c9-cf70-4c2d-9a45-7c4077be1d56"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseRewindSpeed1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7199439d-b5c9-4ccf-b45a-14ac77c4c351"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseRewindSpeed1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""764a9ca3-fd40-449b-871b-ec1abf6c3e6c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreaseRewindSpeed1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SideScrollMap
        m_SideScrollMap = asset.FindActionMap("SideScrollMap", throwIfNotFound: true);
        m_SideScrollMap_HorizontalMovement = m_SideScrollMap.FindAction("HorizontalMovement", throwIfNotFound: true);
        m_SideScrollMap_Jump = m_SideScrollMap.FindAction("Jump", throwIfNotFound: true);
        m_SideScrollMap_Rewind = m_SideScrollMap.FindAction("Rewind", throwIfNotFound: true);
        m_SideScrollMap_Interact = m_SideScrollMap.FindAction("Interact", throwIfNotFound: true);
        m_SideScrollMap_PickUpDrop = m_SideScrollMap.FindAction("PickUpDrop", throwIfNotFound: true);
        m_SideScrollMap_IncreaseRewindSpeed = m_SideScrollMap.FindAction("IncreaseRewindSpeed", throwIfNotFound: true);
        m_SideScrollMap_DecreaseRewindSpeed1 = m_SideScrollMap.FindAction("DecreaseRewindSpeed1", throwIfNotFound: true);
    }

    ~@BraidInputActions()
    {
        Debug.Assert(!m_SideScrollMap.enabled, "This will cause a leak and performance issues, BraidInputActions.SideScrollMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SideScrollMap
    private readonly InputActionMap m_SideScrollMap;
    private List<ISideScrollMapActions> m_SideScrollMapActionsCallbackInterfaces = new List<ISideScrollMapActions>();
    private readonly InputAction m_SideScrollMap_HorizontalMovement;
    private readonly InputAction m_SideScrollMap_Jump;
    private readonly InputAction m_SideScrollMap_Rewind;
    private readonly InputAction m_SideScrollMap_Interact;
    private readonly InputAction m_SideScrollMap_PickUpDrop;
    private readonly InputAction m_SideScrollMap_IncreaseRewindSpeed;
    private readonly InputAction m_SideScrollMap_DecreaseRewindSpeed1;
    public struct SideScrollMapActions
    {
        private @BraidInputActions m_Wrapper;
        public SideScrollMapActions(@BraidInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @HorizontalMovement => m_Wrapper.m_SideScrollMap_HorizontalMovement;
        public InputAction @Jump => m_Wrapper.m_SideScrollMap_Jump;
        public InputAction @Rewind => m_Wrapper.m_SideScrollMap_Rewind;
        public InputAction @Interact => m_Wrapper.m_SideScrollMap_Interact;
        public InputAction @PickUpDrop => m_Wrapper.m_SideScrollMap_PickUpDrop;
        public InputAction @IncreaseRewindSpeed => m_Wrapper.m_SideScrollMap_IncreaseRewindSpeed;
        public InputAction @DecreaseRewindSpeed1 => m_Wrapper.m_SideScrollMap_DecreaseRewindSpeed1;
        public InputActionMap Get() { return m_Wrapper.m_SideScrollMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SideScrollMapActions set) { return set.Get(); }
        public void AddCallbacks(ISideScrollMapActions instance)
        {
            if (instance == null || m_Wrapper.m_SideScrollMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SideScrollMapActionsCallbackInterfaces.Add(instance);
            @HorizontalMovement.started += instance.OnHorizontalMovement;
            @HorizontalMovement.performed += instance.OnHorizontalMovement;
            @HorizontalMovement.canceled += instance.OnHorizontalMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Rewind.started += instance.OnRewind;
            @Rewind.performed += instance.OnRewind;
            @Rewind.canceled += instance.OnRewind;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @PickUpDrop.started += instance.OnPickUpDrop;
            @PickUpDrop.performed += instance.OnPickUpDrop;
            @PickUpDrop.canceled += instance.OnPickUpDrop;
            @IncreaseRewindSpeed.started += instance.OnIncreaseRewindSpeed;
            @IncreaseRewindSpeed.performed += instance.OnIncreaseRewindSpeed;
            @IncreaseRewindSpeed.canceled += instance.OnIncreaseRewindSpeed;
            @DecreaseRewindSpeed1.started += instance.OnDecreaseRewindSpeed1;
            @DecreaseRewindSpeed1.performed += instance.OnDecreaseRewindSpeed1;
            @DecreaseRewindSpeed1.canceled += instance.OnDecreaseRewindSpeed1;
        }

        private void UnregisterCallbacks(ISideScrollMapActions instance)
        {
            @HorizontalMovement.started -= instance.OnHorizontalMovement;
            @HorizontalMovement.performed -= instance.OnHorizontalMovement;
            @HorizontalMovement.canceled -= instance.OnHorizontalMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Rewind.started -= instance.OnRewind;
            @Rewind.performed -= instance.OnRewind;
            @Rewind.canceled -= instance.OnRewind;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @PickUpDrop.started -= instance.OnPickUpDrop;
            @PickUpDrop.performed -= instance.OnPickUpDrop;
            @PickUpDrop.canceled -= instance.OnPickUpDrop;
            @IncreaseRewindSpeed.started -= instance.OnIncreaseRewindSpeed;
            @IncreaseRewindSpeed.performed -= instance.OnIncreaseRewindSpeed;
            @IncreaseRewindSpeed.canceled -= instance.OnIncreaseRewindSpeed;
            @DecreaseRewindSpeed1.started -= instance.OnDecreaseRewindSpeed1;
            @DecreaseRewindSpeed1.performed -= instance.OnDecreaseRewindSpeed1;
            @DecreaseRewindSpeed1.canceled -= instance.OnDecreaseRewindSpeed1;
        }

        public void RemoveCallbacks(ISideScrollMapActions instance)
        {
            if (m_Wrapper.m_SideScrollMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISideScrollMapActions instance)
        {
            foreach (var item in m_Wrapper.m_SideScrollMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SideScrollMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SideScrollMapActions @SideScrollMap => new SideScrollMapActions(this);
    public interface ISideScrollMapActions
    {
        void OnHorizontalMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRewind(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnPickUpDrop(InputAction.CallbackContext context);
        void OnIncreaseRewindSpeed(InputAction.CallbackContext context);
        void OnDecreaseRewindSpeed1(InputAction.CallbackContext context);
    }
}
